### ISSUE TITLE
ERROR - NVIDIAInfo Windows CCD settings were not applied correctly.

### ISSUE THREAD

**Issue by DocMAX** [terrymacdonald/NVIDIAInfo#1]
I can't switch back to Nvidia Surround from Tripple Screen. Check Log
[NVIDIAInfo.log](https://github.com/terrymacdonald/NVIDIAInfo/files/7799728/NVIDIAInfo.log)
.

**Comment by terrymacdonald** [comment]
Hi @DocMAX 

Apologies for the delay, I spend most of my time in my DisplayMagician project (the app that uses the NVIDIALibrary that this program tests) so I don't check here that often.

Are you able to send through your .cfg files for me to review please? The log unfortunately only shows that there was some kind of error applying the windows display settings.

Are you on Win 11 or Win 10? If you have recently moved to Windows 11, then you cannot re-use any Windows 10 configuration files in Win 11. You need to  delete the Win 10 cfg files and re-create and save them again in Win 11.

What video card are you using? What sort of NVIDIA make and model is it?

Thanks
Terry

**Comment by terrymacdonald** [comment]
@DocMAX please try with NVIDIAInfo v1.7.0 which I just released today. It has a LOT of fixes applied.

**Comment by terrymacdonald** [comment]
I'm going to close this issue for now. I've not had any response back for a while now, and I would like to tidy this up. Feel free to reopen this issue if you are still experiencing the same problem. 

Thanks
Terry
